#ifndef TECMO_ASSET_PACK_GAMEPLAY_PRETIP_H
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_H

#include "tecmo_gameplay_pretip.h"

#include <stddef.h>
#include <stdint.h>

#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_ID "gameplay/pre-tip"
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_VERSION 2U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_HEADER_SIZE 512U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_SOURCE_STRIDE 32U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_SOURCES_OFFSET 512U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_DESCRIPTOR_OFFSET 1536U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_ENCODED_OFFSET 1568U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_DECODED_OFFSET 1600U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_PALETTE_OFFSET 3648U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_WAIT_OFFSET 3680U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_SEQUENCE_OFFSET 3744U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_STRINGS_OFFSET 4064U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_POINTERS_OFFSET 4128U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_CHARMAP_OFFSET 4160U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_CHARACTER_TILES_OFFSET 4256U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TEXT_CHR_SELECTORS_OFFSET 4416U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_CLOSEUP_ENTRY_OFFSET 4448U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_CLOSEUP_PALETTE_OFFSET 4992U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_CLOSEUP_CONTROL_OFFSET 5088U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_CLOSEUP_TIMING_OFFSET 5376U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_CLOSEUP_SPRITE_STAGING_OFFSET 5472U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_SETUP_OFFSET 5696U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_SETUP_CPU_OFFSET 0x985BU
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_INPUT_CPU_OFFSET 0x985EU
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_INPUT_OFFSET \
    (TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_SETUP_OFFSET + \
     (TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_INPUT_CPU_OFFSET - \
      TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_SETUP_CPU_OFFSET))
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_INPUT_SIZE 13U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_INPUT_FNV1A32 0x423816F1U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_INPUT_FNV1A64 \
    0x032F8A7A4F4439D1ULL
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_AWAY_ACTOR_OFFSET 178U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_HOME_ACTOR_OFFSET 179U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_UPDATE_OFFSET 5760U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_LAUNCH_BRIDGE_OFFSET 6144U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_HANDOFF_OFFSET 6336U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_ORIENTATION_OFFSET 6496U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_MECHANICS_OFFSET 6560U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_MECHANICS_SIZE \
    TECMO_GAMEPLAY_PRETIP_TPM2_SIZE
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_EXACT_SOURCE_OFFSET 7008U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_CAPTURE_ERROR_OFFSET \
    (TECMO_ASSET_PACK_GAMEPLAY_PRETIP_CLOSEUP_ENTRY_OFFSET + \
     (0x86E1U - 0x86ABU))
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_ACTOR_DISPATCHER_OFFSET 7008U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_AUTOMATIC_ACTOR_OFFSET 7088U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_OPPOSING_DISPATCHER_OFFSET 7200U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_OPPOSING_ACTOR_OFFSET \
    (TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TIP_SETUP_OFFSET + \
     (0x985EU - 0x985BU))
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_JUMP_COMMIT_OFFSET 7312U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_SLOT10_CLAIM_OFFSET 7392U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_E56E_HOOK_OFFSET 7600U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_RNG_MIX_OFFSET 7616U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_SIZE 7680U
/* Ordinary FNV identities of the exact stored payload, including metadata. */
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_FNV1A32 0x28910BC1U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_FNV1A64 0x7EA1596E8DFAC0C1ULL

#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_DEPENDENCY_COUNT 6U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TGJS_SIZE 2776U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TGJS_FNV1A32 0xA66EE873U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TGJS_VERSION 2U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TGJS_HEADER_SIZE 256U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_HEADER_RESERVED_ZERO_START 208U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_HEADER_RESERVED_ZERO_END 220U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TGJS_SIZE_OFFSET 220U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TGJS_FNV32_OFFSET 224U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TGJS_VERSION_OFFSET 228U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TGJS_HEADER_OFFSET 230U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TPM2_OFFSET_FIELD 196U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TPM2_SIZE_FIELD 200U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_EXACT_SOURCE_BASE_FIELD 204U

#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TWAR_SIZE 21024U
#define TECMO_ASSET_PACK_GAMEPLAY_PRETIP_TWAR_FNV1A32 0x3B22C51BU

typedef struct TecmoGameplayPreTipExpectedSource {
    TecmoGameplayPreTipSourceKind kind;
    uint8_t bank;
    uint8_t fixed_bank;
    uint16_t cpu_start;
    uint32_t byte_count;
    uint32_t fingerprint_fnv1a32;
    uint64_t fingerprint_fnv1a64;
    uint32_t payload_offset;
} TecmoGameplayPreTipExpectedSource;

typedef struct TecmoGameplayPreTipProvenance {
    uint64_t source_offsets[TECMO_GAMEPLAY_PRETIP_SOURCE_COUNT];
} TecmoGameplayPreTipProvenance;

extern const TecmoGameplayPreTipExpectedSource
    tecmo_gameplay_pretip_expected_sources[
        TECMO_GAMEPLAY_PRETIP_SOURCE_COUNT];

int tecmo_asset_pack_build_gameplay_pretip(
    const uint8_t *rom,
    uint64_t rom_size,
    uint64_t prg_offset,
    uint32_t prg_banks,
    int enforce_revision_fingerprints,
    uint8_t *payload,
    size_t payload_size,
    TecmoGameplayPreTipProvenance *provenance,
    char *message,
    size_t message_size);

#endif
