#ifndef TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_H
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_H

#include "tecmo_gameplay_shot_resolution.h"
#include "tecmo_asset_pack_import_layout.h"

#include <stddef.h>
#include <stdint.h>

#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_VERSION 4U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_BANK 5U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_HEADER_SIZE 128U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_SOURCE_STRIDE 32U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_SOURCES_OFFSET 128U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_METADATA_OFFSET 352U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_METADATA_SIZE 64U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_ROUTE_OFFSET 416U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_ROUTE_STRIDE 8U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_POINT_ARC_OFFSET 448U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_POINT_ARC_CPU 0xBEEFU
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_POINT_ARC_SIZE 124U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_POINT_ARC_FNV1A32 \
    0x9EF1061BU
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_POINT_ARC_FNV1A64 \
    0xE8A0728513DD8BDBULL
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_POINT_CLASSIFIER_CPU 0xB995U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_POINT_CLASSIFIER_END_CPU \
    0xBA3FU
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_PADDING_OFFSET 572U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_PADDING_SIZE 36U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_SIZE 608U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_CONVERGENCE_CPU 0xA2DFU
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_CONVERGENCE_SIZE 25U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_CONVERGENCE_FNV1A32 \
    0x9D918043U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_CONVERGENCE_FNV1A64 \
    0xB156545B031B1B23ULL
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_RATTLE_TARGET_CPU 0xAD4EU
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_RATTLE_TARGET_SIZE 23U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_RATTLE_TARGET_FNV1A32 \
    0xAF1D6B17U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_RATTLE_TARGET_FNV1A64 \
    0xE14CD1782E18BC97ULL
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_RATTLE_SNAP_CPU 0xBDF3U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_RATTLE_SNAP_SIZE 4U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_RATTLE_SNAP_FNV1A32 \
    0x79F66DB3U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_RATTLE_SNAP_FNV1A64 \
    0x59420E49CA612933ULL

/* Filled from the exact Rev1 ROM and the canonical native payload. */
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_METADATA_FNV1A32 \
    0x063955B1U
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_METADATA_FNV1A64 \
    0xF100850921E96471ULL
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_ROUTES_FNV1A32 \
    0xD5CB247FU
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_ROUTES_FNV1A64 \
    0x9BA367FC638FB99FULL
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_FNV1A32 0x5376E82BU
#define TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_FNV1A64 \
    0xFACCE42B52382D6BULL

typedef struct TecmoGameplayShotResolutionExpectedSource {
    TecmoGameplayShotResolutionSourceKind kind;
    uint16_t cpu_start;
    uint32_t byte_count;
    uint32_t fingerprint_fnv1a32;
    uint64_t fingerprint_fnv1a64;
} TecmoGameplayShotResolutionExpectedSource;

typedef struct TecmoGameplayShotResolutionProvenance {
    uint64_t source_offsets[TECMO_GAMEPLAY_SHOT_RESOLUTION_SOURCE_COUNT];
    uint64_t convergence_predicate_offset;
    uint64_t rim_rattle_launch_target_offset;
    uint64_t rim_rattle_snap_table_offset;
    uint64_t point_arc_table_offset;
} TecmoGameplayShotResolutionProvenance;

extern const TecmoGameplayShotResolutionExpectedSource
    tecmo_gameplay_shot_resolution_expected_sources[
        TECMO_GAMEPLAY_SHOT_RESOLUTION_SOURCE_COUNT];
extern const uint8_t tecmo_gameplay_shot_resolution_expected_metadata[
    TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_METADATA_SIZE];
extern const uint8_t tecmo_gameplay_shot_resolution_expected_routes[
    TECMO_GAMEPLAY_SHOT_RESOLUTION_RIM_ROUTE_COUNT *
        TECMO_ASSET_PACK_GAMEPLAY_SHOT_RESOLUTION_ROUTE_STRIDE];

int tecmo_asset_pack_build_gameplay_shot_resolution(
    const uint8_t *rom,
    uint64_t rom_size,
    uint64_t prg_offset,
    uint32_t prg_banks,
    int enforce_revision_fingerprints,
    uint8_t *payload,
    size_t payload_size,
    TecmoGameplayShotResolutionProvenance *provenance,
    char *message,
    size_t message_size);

int tecmo_asset_pack_gameplay_shot_resolution_self_test(
    char *message,
    size_t message_size);

#endif
