#ifndef TECMO_ASSET_PACK_IMPORT_LAYOUT_H
#define TECMO_ASSET_PACK_IMPORT_LAYOUT_H

#include <stdint.h>

#define TECMO_ASSET_PACK_PRG_BANK_BYTES 0x4000ULL
#define TECMO_ASSET_PACK_CHR_BANK_BYTES 0x2000ULL
#define TECMO_ASSET_PACK_PATH_SIZE 1024U
#define TECMO_ASSET_PACK_ARENA_INTRO_SCRIPT_ID "arena/intro/script"
#define TECMO_ASSET_PACK_ARENA_INTRO_BACKGROUND_ID "arena/intro/background-layer"
#define TECMO_ASSET_PACK_ARENA_INTRO_PALETTE_ID "arena/intro/palette-cycle"
#define TECMO_ASSET_PACK_ARENA_INTRO_SPRITE_GROUPS_ID "arena/intro/sprite-groups"
#define TECMO_ASSET_PACK_READY_ID "arena/intro/ready-screen"
#define TECMO_ASSET_PACK_WARRIORS_ID "arena/intro/warriors-transition"
#define TECMO_ASSET_PACK_CLIPPERS_ID "arena/intro/clippers-transition"
#define TECMO_ASSET_PACK_BUCKS_ID "arena/intro/bucks-transition"
#define TECMO_ASSET_PACK_PASS_ID "arena/intro/pass-transition"
#define TECMO_ASSET_PACK_FINALE_ID "intro/finale-sequence"
#define TECMO_ASSET_PACK_TITLE_ATTRACT_ID "title/attract-continuation"
#define TECMO_ASSET_PACK_TITLE_SCREEN_ID "title/start-screen"
#define TECMO_ASSET_PACK_START_GAME_MENU_ID "menu/start-game"
#define TECMO_ASSET_PACK_PRESEASON_MENU_ID "menu/preseason"
#define TECMO_ASSET_PACK_MUSIC_ID "audio/music"
#define TECMO_ASSET_PACK_MUSIC_BANK 4U
#define TECMO_ASSET_PACK_MUSIC_DIRECTORY_CPU 0x8CD0U
#define TECMO_ASSET_PACK_MUSIC_DIRECTORY_SIZE 18U
#define TECMO_ASSET_PACK_MUSIC_SOURCE_CPU 0x8AA4U
#define TECMO_ASSET_PACK_MUSIC_SOURCE_SIZE 5218U
#define TECMO_ASSET_PACK_MUSIC_ENGINE_CPU 0xF2F2U
#define TECMO_ASSET_PACK_MUSIC_ENGINE_SIZE 1759U
#define TECMO_ASSET_PACK_MUSIC_PITCH_CPU 0xF93BU
#define TECMO_ASSET_PACK_MUSIC_PITCH_COUNT 75U
#define TECMO_ASSET_PACK_MUSIC_TRACK_COUNT 4U
#define TECMO_ASSET_PACK_MUSIC_CHANNEL_COUNT 4U
#define TECMO_ASSET_PACK_MUSIC_HEADER_SIZE 128U
#define TECMO_ASSET_PACK_MUSIC_TRACK_STRIDE 48U
#define TECMO_ASSET_PACK_MUSIC_VOICE_STRIDE 8U
#define TECMO_ASSET_PACK_MUSIC_INSTRUCTION_STRIDE 16U
#define TECMO_ASSET_PACK_MUSIC_MAX_VOICES 64U
#define TECMO_ASSET_PACK_MUSIC_MAX_INSTRUCTIONS 8192U
#define TECMO_ASSET_PACK_MUSIC_MAX_CHANNEL_INSTRUCTIONS 1024U
#define TECMO_ASSET_PACK_MUSIC_MAX_LOOPS 32U
#define TECMO_ASSET_PACK_MUSIC_LOOP_STATE_COUNT 1U
#define TECMO_ASSET_PACK_MUSIC_MAX_CALL_DEPTH 16U
#define TECMO_ASSET_PACK_MUSIC_SAMPLE_RATE 44100U
#define TECMO_ASSET_PACK_MUSIC_TICK_NUMERATOR 39375000U
#define TECMO_ASSET_PACK_MUSIC_TICK_DENOMINATOR 655171U
#define TECMO_ASSET_PACK_PRESENTS_ID "intro/tecmo-presents-screen"
#define TECMO_ASSET_PACK_LICENSE_ID "intro/nba-license-screen"
#define TECMO_ASSET_PACK_OPENING_SCREEN_HEADER_SIZE 64U
#define TECMO_ASSET_PACK_OPENING_SCREEN_WIDTH 32U
#define TECMO_ASSET_PACK_OPENING_SCREEN_HEIGHT 30U
#define TECMO_ASSET_PACK_OPENING_SCREEN_CELL_COUNT 960U
#define TECMO_ASSET_PACK_OPENING_SCREEN_CELL_STRIDE 6U
#define TECMO_ASSET_PACK_OPENING_SCREEN_CELLS_OFFSET 64U
#define TECMO_ASSET_PACK_OPENING_SCREEN_PALETTES_OFFSET \
    (TECMO_ASSET_PACK_OPENING_SCREEN_CELLS_OFFSET + \
     TECMO_ASSET_PACK_OPENING_SCREEN_CELL_COUNT * \
         TECMO_ASSET_PACK_OPENING_SCREEN_CELL_STRIDE)
#define TECMO_ASSET_PACK_PRESENTS_SCREEN_ID 0U
#define TECMO_ASSET_PACK_LICENSE_SCREEN_ID 2U
#define TECMO_ASSET_PACK_PRESENTS_STREAM_CPU 0x84FBU
#define TECMO_ASSET_PACK_LICENSE_STREAM_CPU 0x856EU
#define TECMO_ASSET_PACK_OPENING_PALETTE_CPU 0x9376U
#define TECMO_ASSET_PACK_PRESENTS_STREAM_SIZE 116U
#define TECMO_ASSET_PACK_LICENSE_STREAM_SIZE 177U
#define TECMO_ASSET_PACK_PRESENTS_STAGE_COUNT 9U
#define TECMO_ASSET_PACK_LICENSE_STAGE_COUNT 6U
#define TECMO_ASSET_PACK_PRESENTS_PALETTE_STRIDE 32U
#define TECMO_ASSET_PACK_LICENSE_PALETTE_STRIDE 16U
#define TECMO_ASSET_PACK_PRESENTS_SPRITE_COUNT 20U
#define TECMO_ASSET_PACK_PRESENTS_SPRITE_STRIDE 12U
#define TECMO_ASSET_PACK_PRESENTS_SPRITE_TABLE_CPU 0xBDD6U
#define TECMO_ASSET_PACK_PRESENTS_SPRITE_PALETTE_CPU 0xBE27U
#define TECMO_ASSET_PACK_PRESENTS_SPRITE_RECORD_FINGERPRINT 0xA3E8B4F0U
#define TECMO_ASSET_PACK_PRESENTS_SPRITE_PALETTE_FINGERPRINT 0xACF5D9A1U
#define TECMO_ASSET_PACK_OPENING_BG_PALETTE_FINGERPRINT 0x761B572DU
#define TECMO_ASSET_PACK_PRESENTS_BG_R0 0xFCU
#define TECMO_ASSET_PACK_PRESENTS_BG_R1 0xFAU
#define TECMO_ASSET_PACK_PRESENTS_SPRITE_R2 0xF4U
#define TECMO_ASSET_PACK_PRESENTS_SPRITE_R3 0xF5U
#define TECMO_ASSET_PACK_PRESENTS_SELECTOR_CODE_CPU 0xBC90U
#define TECMO_ASSET_PACK_PRESENTS_Y_BASE_OPERAND_CPU 0xBDA8U
#define TECMO_ASSET_PACK_PRESENTS_TILE_BASE_OPERAND_CPU 0xBDB2U
#define TECMO_ASSET_PACK_PRESENTS_X_BASE_OPERAND_CPU 0xBDC3U
#define TECMO_ASSET_PACK_PRESENTS_DURATION 133U
#define TECMO_ASSET_PACK_LICENSE_DURATION 277U
#define TECMO_ASSET_PACK_PRESENTS_SPRITE_HIDE_FRAME 131U
#define TECMO_ASSET_PACK_PRESENTS_SIZE \
    (TECMO_ASSET_PACK_OPENING_SCREEN_PALETTES_OFFSET + \
     TECMO_ASSET_PACK_PRESENTS_STAGE_COUNT * \
         TECMO_ASSET_PACK_PRESENTS_PALETTE_STRIDE + \
     TECMO_ASSET_PACK_PRESENTS_STAGE_COUNT * 2U + \
     TECMO_ASSET_PACK_PRESENTS_SPRITE_COUNT * \
         TECMO_ASSET_PACK_PRESENTS_SPRITE_STRIDE)
#define TECMO_ASSET_PACK_LICENSE_SIZE \
    (TECMO_ASSET_PACK_OPENING_SCREEN_PALETTES_OFFSET + \
     TECMO_ASSET_PACK_LICENSE_STAGE_COUNT * \
         TECMO_ASSET_PACK_LICENSE_PALETTE_STRIDE + \
     TECMO_ASSET_PACK_LICENSE_STAGE_COUNT * 2U)
#define TECMO_ASSET_PACK_ARENA_BANK04 4U
#define TECMO_ASSET_PACK_ARENA_ROUTE_CPU 0x88E8U
#define TECMO_ASSET_PACK_ARENA_PALETTE_CPU 0x89DDU
#define TECMO_ASSET_PACK_ARENA_SEEDS_CPU 0x8984U
#define TECMO_ASSET_PACK_ARENA_SPRITE_EMIT_CPU 0x8988U
#define TECMO_ASSET_PACK_ARENA_SPRITE_EMIT_SIZE 53U
#define TECMO_ASSET_PACK_ARENA_PARAMS_CPU 0x89BDU
#define TECMO_ASSET_PACK_ARENA_POINTER_TABLE_CPU 0xA7DBU
#define TECMO_ASSET_PACK_ARENA_JUMBOTRON_COUNT 55U
#define TECMO_ASSET_PACK_ARENA_GOAL_COUNT 16U
#define TECMO_ASSET_PACK_ARENA_SPRITE_PIECE_COUNT 71U
#define TECMO_ASSET_PACK_ARENA_SPRITE_GROUP_HEADER_SIZE 48U
#define TECMO_ASSET_PACK_ARENA_SPRITE_GROUP_STRIDE 20U
#define TECMO_ASSET_PACK_ARENA_SPRITE_PIECE_STRIDE 12U
#define TECMO_ASSET_PACK_ARENA_SPRITE_PALETTE_OFFSET 48U
#define TECMO_ASSET_PACK_ARENA_SPRITE_GROUPS_OFFSET 64U
#define TECMO_ASSET_PACK_ARENA_SPRITE_PIECES_OFFSET 104U
#define TECMO_ASSET_PACK_ARENA_SPRITE_GROUPS_SIZE \
    (TECMO_ASSET_PACK_ARENA_SPRITE_PIECES_OFFSET + \
     TECMO_ASSET_PACK_ARENA_SPRITE_PIECE_COUNT * \
         TECMO_ASSET_PACK_ARENA_SPRITE_PIECE_STRIDE)
#define TECMO_ASSET_PACK_ARENA_SPRITE_CHR_BASE 8192U
#define TECMO_ASSET_PACK_ARENA_SPRITE_CHR_LIMIT \
    (TECMO_ASSET_PACK_ARENA_SPRITE_CHR_BASE + 2U * 1024U)
#define TECMO_ASSET_PACK_ARENA_GOAL_CONNECTOR_RAW_Y 0xE0U
#define TECMO_ASSET_PACK_ARENA_GOAL_CONNECTOR_RAW_X 0xFDU
#define TECMO_ASSET_PACK_ARENA_GOAL_CONNECTOR_RAW_TILE 0x36U
#define TECMO_ASSET_PACK_ARENA_GOAL_CONNECTOR_RAW_ATTRIBUTES 0x02U
#define TECMO_ASSET_PACK_ARENA_GOAL_CONNECTOR_TOP_CHR_OFFSET \
    (TECMO_ASSET_PACK_ARENA_SPRITE_CHR_BASE + \
     TECMO_ASSET_PACK_ARENA_GOAL_CONNECTOR_RAW_TILE * 16U)
#define TECMO_ASSET_PACK_ARENA_GOAL_CONNECTOR_OVERLAY_Y_ADJUST (-1)
#define TECMO_ASSET_PACK_ARENA_SPRITE_CHR_R2 8U
#define TECMO_ASSET_PACK_ARENA_SPRITE_CHR_R3 9U
#define TECMO_ASSET_PACK_SWITCHED_PRG_CPU_BASE 0x8000U
#define TECMO_ASSET_PACK_SWITCHED_PRG_CPU_LIMIT 0xC000U
#define TECMO_ASSET_PACK_SCREEN_DESCRIPTOR_CPU 0xDC85U
#define TECMO_ASSET_PACK_ARENA_SCREEN_ID 0x18U
#define TECMO_ASSET_PACK_SCREEN_DESCRIPTOR_SIZE 7U
#define TECMO_ASSET_PACK_SCREEN_DECODED_SIZE 2048U
#define TECMO_ASSET_PACK_NAMETABLE_SIZE 1024U
#define TECMO_ASSET_PACK_ATTRIBUTE_OFFSET 0x3C0U
#define TECMO_ASSET_PACK_ARENA_LAYER_WIDTH 32U
#define TECMO_ASSET_PACK_ARENA_LAYER_HEIGHT 51U
#define TECMO_ASSET_PACK_ARENA_LAYER_CELL_STRIDE 6U
#define TECMO_ASSET_PACK_ARENA_LAYER_HEADER_SIZE 48U
#define TECMO_ASSET_PACK_ARENA_LAYER_CELL_COUNT \
    (TECMO_ASSET_PACK_ARENA_LAYER_WIDTH * TECMO_ASSET_PACK_ARENA_LAYER_HEIGHT)
#define TECMO_ASSET_PACK_ARENA_LAYER_SIZE \
    (TECMO_ASSET_PACK_ARENA_LAYER_HEADER_SIZE + \
     TECMO_ASSET_PACK_ARENA_LAYER_CELL_COUNT * TECMO_ASSET_PACK_ARENA_LAYER_CELL_STRIDE)
#define TECMO_ASSET_PACK_ARENA_BACKGROUND_ROUTE_CPU 0x88E8U
#define TECMO_ASSET_PACK_ARENA_LOWER_R0_TABLE_CPU 0xFD7CU
#define TECMO_ASSET_PACK_ARENA_LOWER_R1_TABLE_CPU 0xFD80U
#define TECMO_ASSET_PACK_ARENA_LOWER_SELECTOR_INDEX 1U
#define TECMO_ASSET_PACK_ARENA_DECODER_CPU 0xD9F6U
#define TECMO_ASSET_PACK_READY_ROUTE_CPU 0x8483U
#define TECMO_ASSET_PACK_READY_SCREEN_ID 0x1EU
#define TECMO_ASSET_PACK_READY_SCRIPT_CPU 0x84DCU
#define TECMO_ASSET_PACK_READY_SCRIPT_SIZE 48U
#define TECMO_ASSET_PACK_READY_HEADER_SIZE 64U
#define TECMO_ASSET_PACK_READY_CELL_STRIDE 6U
#define TECMO_ASSET_PACK_READY_PALETTES_OFFSET 64U
#define TECMO_ASSET_PACK_READY_PALETTE_FRAMES_OFFSET 144U
#define TECMO_ASSET_PACK_READY_MASKS_OFFSET 149U
#define TECMO_ASSET_PACK_READY_CELLS_OFFSET 245U
#define TECMO_ASSET_PACK_READY_CELL_COUNT 960U
#define TECMO_ASSET_PACK_READY_SIZE \
    (TECMO_ASSET_PACK_READY_CELLS_OFFSET + \
     TECMO_ASSET_PACK_READY_CELL_COUNT * TECMO_ASSET_PACK_READY_CELL_STRIDE)
#define TECMO_ASSET_PACK_WARRIORS_ROUTE_CPU 0x86D0U
#define TECMO_ASSET_PACK_WARRIORS_SCREEN_ID 0x1AU
#define TECMO_ASSET_PACK_WARRIORS_DECODED_SIZE 1984U
#define TECMO_ASSET_PACK_WARRIORS_HEADER_SIZE 96U
#define TECMO_ASSET_PACK_WARRIORS_CELL_STRIDE 10U
#define TECMO_ASSET_PACK_WARRIORS_PAGE_COUNT 2U
#define TECMO_ASSET_PACK_WARRIORS_TILES_PER_PAGE 960U
#define TECMO_ASSET_PACK_WARRIORS_BG_R1_LOWER 0xFAU
#define TECMO_ASSET_PACK_WARRIORS_SPRITE_PALETTE_CPU 0x89EDU
#define TECMO_ASSET_PACK_WARRIORS_POINTER_CPU 0xA90FU
#define TECMO_ASSET_PACK_WARRIORS_STREAM_CPU 0xA919U
#define TECMO_ASSET_PACK_WARRIORS_PIECE_COUNT 46U
#define TECMO_ASSET_PACK_WARRIORS_PIECE_STRIDE 16U
#define TECMO_ASSET_PACK_WARRIORS_PATCH_COUNT 2U
#define TECMO_ASSET_PACK_WARRIORS_PATCH_TILE_COUNT 64U
#define TECMO_ASSET_PACK_WARRIORS_PATCH_STRIDE 6U
#define TECMO_ASSET_PACK_WARRIORS_WORDMARK_GLYPH_COUNT 8U
#define TECMO_ASSET_PACK_WARRIORS_WORDMARK_TILE_COUNT 32U
#define TECMO_ASSET_PACK_WARRIORS_WORDMARK_STRIDE 6U
#define TECMO_ASSET_PACK_WARRIORS_WORDMARK_BANK 6U
#define TECMO_ASSET_PACK_WARRIORS_PATCH0_CPU 0xBCACU
#define TECMO_ASSET_PACK_WARRIORS_PATCH1_CPU 0xBCECU
#define TECMO_ASSET_PACK_WARRIORS_BG_PALETTE_OFFSET 96U
#define TECMO_ASSET_PACK_WARRIORS_SPRITE_PALETTE_OFFSET 112U
#define TECMO_ASSET_PACK_WARRIORS_PAGES_OFFSET 128U
#define TECMO_ASSET_PACK_WARRIORS_PIECES_OFFSET \
    (TECMO_ASSET_PACK_WARRIORS_PAGES_OFFSET + \
     TECMO_ASSET_PACK_WARRIORS_PAGE_COUNT * TECMO_ASSET_PACK_WARRIORS_TILES_PER_PAGE * \
         TECMO_ASSET_PACK_WARRIORS_CELL_STRIDE)
#define TECMO_ASSET_PACK_WARRIORS_PATCHES_OFFSET \
    (TECMO_ASSET_PACK_WARRIORS_PIECES_OFFSET + \
     TECMO_ASSET_PACK_WARRIORS_PIECE_COUNT * TECMO_ASSET_PACK_WARRIORS_PIECE_STRIDE)
#define TECMO_ASSET_PACK_WARRIORS_WORDMARK_OFFSET \
    (TECMO_ASSET_PACK_WARRIORS_PATCHES_OFFSET + \
     TECMO_ASSET_PACK_WARRIORS_PATCH_COUNT * TECMO_ASSET_PACK_WARRIORS_PATCH_TILE_COUNT * \
         TECMO_ASSET_PACK_WARRIORS_PATCH_STRIDE)
#define TECMO_ASSET_PACK_WARRIORS_SIZE \
    (TECMO_ASSET_PACK_WARRIORS_WORDMARK_OFFSET + \
     TECMO_ASSET_PACK_WARRIORS_WORDMARK_TILE_COUNT * \
         TECMO_ASSET_PACK_WARRIORS_WORDMARK_STRIDE)
#define TECMO_ASSET_PACK_CLIPPERS_ROUTE_CPU 0x865EU
#define TECMO_ASSET_PACK_CLIPPERS_SCREEN_ID 0x1BU
#define TECMO_ASSET_PACK_CLIPPERS_HEADER_SIZE 96U
#define TECMO_ASSET_PACK_CLIPPERS_CELL_STRIDE 10U
#define TECMO_ASSET_PACK_CLIPPERS_CELL_COUNT 1920U
#define TECMO_ASSET_PACK_CLIPPERS_PALETTES_OFFSET 96U
#define TECMO_ASSET_PACK_CLIPPERS_CELLS_OFFSET 160U
#define TECMO_ASSET_PACK_CLIPPERS_WORDMARK_TILE_COUNT 32U
#define TECMO_ASSET_PACK_CLIPPERS_WORDMARK_OFFSET \
    (TECMO_ASSET_PACK_CLIPPERS_CELLS_OFFSET + \
     TECMO_ASSET_PACK_CLIPPERS_CELL_COUNT * TECMO_ASSET_PACK_CLIPPERS_CELL_STRIDE)
#define TECMO_ASSET_PACK_CLIPPERS_SIZE \
    (TECMO_ASSET_PACK_CLIPPERS_WORDMARK_OFFSET + \
     TECMO_ASSET_PACK_CLIPPERS_WORDMARK_TILE_COUNT * TECMO_ASSET_PACK_CLIPPERS_CELL_STRIDE)
#define TECMO_ASSET_PACK_CLIPPERS_LOWER_R0 0x2CU
#define TECMO_ASSET_PACK_CLIPPERS_LOWER_R1 0xFAU
#define TECMO_ASSET_PACK_BUCKS_ROUTE_CPU 0x883DU
#define TECMO_ASSET_PACK_BUCKS_SCREEN_ID 0x19U
#define TECMO_ASSET_PACK_BUCKS_HEADER_SIZE 96U
#define TECMO_ASSET_PACK_BUCKS_CELL_STRIDE 10U
#define TECMO_ASSET_PACK_BUCKS_CELL_COUNT 1920U
#define TECMO_ASSET_PACK_BUCKS_PALETTES_OFFSET 96U
#define TECMO_ASSET_PACK_BUCKS_CELLS_OFFSET 160U
#define TECMO_ASSET_PACK_BUCKS_WORDMARK_TILE_COUNT 20U
#define TECMO_ASSET_PACK_BUCKS_WORDMARK_OFFSET \
    (TECMO_ASSET_PACK_BUCKS_CELLS_OFFSET + \
     TECMO_ASSET_PACK_BUCKS_CELL_COUNT * TECMO_ASSET_PACK_BUCKS_CELL_STRIDE)
#define TECMO_ASSET_PACK_BUCKS_SIZE \
    (TECMO_ASSET_PACK_BUCKS_WORDMARK_OFFSET + \
     TECMO_ASSET_PACK_BUCKS_WORDMARK_TILE_COUNT * TECMO_ASSET_PACK_BUCKS_CELL_STRIDE)
#define TECMO_ASSET_PACK_BUCKS_LOWER_R0 0x5EU
#define TECMO_ASSET_PACK_BUCKS_LOWER_R1 0xFAU
#define TECMO_ASSET_PACK_PASS_ROUTE_CPU 0x854FU
#define TECMO_ASSET_PACK_PASS_SCREEN_ID 0x1DU
#define TECMO_ASSET_PACK_PASS_HEADER_SIZE 128U
#define TECMO_ASSET_PACK_PASS_CELL_STRIDE 6U
#define TECMO_ASSET_PACK_PASS_PIECE_COUNT 10U
#define TECMO_ASSET_PACK_PASS_PIECE_STRIDE 16U
#define TECMO_ASSET_PACK_PASS_PALETTES_OFFSET 128U
#define TECMO_ASSET_PACK_PASS_SPRITE_PALETTE_OFFSET 208U
#define TECMO_ASSET_PACK_PASS_CELLS_OFFSET 224U
#define TECMO_ASSET_PACK_PASS_PIECES_OFFSET \
    (TECMO_ASSET_PACK_PASS_CELLS_OFFSET + 1920U * TECMO_ASSET_PACK_PASS_CELL_STRIDE)
#define TECMO_ASSET_PACK_PASS_SIZE \
    (TECMO_ASSET_PACK_PASS_PIECES_OFFSET + \
     TECMO_ASSET_PACK_PASS_PIECE_COUNT * TECMO_ASSET_PACK_PASS_PIECE_STRIDE)
#define TECMO_ASSET_PACK_PASS_HELPER_PALETTE_CPU 0x89FDU
#define TECMO_ASSET_PACK_PASS_SPECIAL_PALETTE_CPU 0x8A1DU
#define TECMO_ASSET_PACK_PASS_POINTER_CPU 0xA90FU
#define TECMO_ASSET_PACK_PASS_STREAM_CPU 0xA9D2U
#define TECMO_ASSET_PACK_FINALE_HEADER_SIZE 192U
#define TECMO_ASSET_PACK_FINALE_SCREEN_COUNT 5U
#define TECMO_ASSET_PACK_FINALE_WIDTH 32U
#define TECMO_ASSET_PACK_FINALE_HEIGHT 30U
#define TECMO_ASSET_PACK_FINALE_PAGE_COUNT 2U
#define TECMO_ASSET_PACK_FINALE_TILES_PER_PAGE 960U
#define TECMO_ASSET_PACK_FINALE_CELLS_PER_SCREEN 1920U
#define TECMO_ASSET_PACK_FINALE_CELL_STRIDE 6U
#define TECMO_ASSET_PACK_FINALE_BACKGROUND_PALETTE_COUNT 5U
#define TECMO_ASSET_PACK_FINALE_REVERSE_PALETTE_COUNT 5U
#define TECMO_ASSET_PACK_FINALE_GROUP_COUNT 2U
#define TECMO_ASSET_PACK_FINALE_GROUP_STRIDE 16U
#define TECMO_ASSET_PACK_FINALE_PIECE_COUNT 10U
#define TECMO_ASSET_PACK_FINALE_PIECE_STRIDE 16U
#define TECMO_ASSET_PACK_FINALE_ROUTE_COUNT 5U
#define TECMO_ASSET_PACK_FINALE_ROUTE_STRIDE 8U
#define TECMO_ASSET_PACK_FINALE_SHORT_ANCHOR_COUNT 9U
#define TECMO_ASSET_PACK_FINALE_ANCHOR_STRIDE 2U
#define TECMO_ASSET_PACK_FINALE_REVERSE_METADATA_SIZE 16U
#define TECMO_ASSET_PACK_FINALE_TITLE_METADATA_SIZE 32U
#define TECMO_ASSET_PACK_FINALE_TITLE_SLOT_COUNT 44U
#define TECMO_ASSET_PACK_FINALE_TITLE_TEXT_SLOT_COUNT 26U
#define TECMO_ASSET_PACK_FINALE_TITLE_SLOT_STRIDE 32U
#define TECMO_ASSET_PACK_FINALE_TITLE_CELL_COUNT 4U
#define TECMO_ASSET_PACK_FINALE_BAND_COUNT 3U
#define TECMO_ASSET_PACK_FINALE_BAND_STRIDE 16U
#define TECMO_ASSET_PACK_FINALE_SCREENS_OFFSET TECMO_ASSET_PACK_FINALE_HEADER_SIZE
#define TECMO_ASSET_PACK_FINALE_BACKGROUND_PALETTES_OFFSET \
    (TECMO_ASSET_PACK_FINALE_SCREENS_OFFSET + \
     TECMO_ASSET_PACK_FINALE_SCREEN_COUNT * \
         TECMO_ASSET_PACK_FINALE_CELLS_PER_SCREEN * \
         TECMO_ASSET_PACK_FINALE_CELL_STRIDE)
#define TECMO_ASSET_PACK_FINALE_REVERSE_PALETTES_OFFSET \
    (TECMO_ASSET_PACK_FINALE_BACKGROUND_PALETTES_OFFSET + \
     TECMO_ASSET_PACK_FINALE_BACKGROUND_PALETTE_COUNT * 16U)
#define TECMO_ASSET_PACK_FINALE_REVERSE_PALETTE_FRAMES_OFFSET \
    (TECMO_ASSET_PACK_FINALE_REVERSE_PALETTES_OFFSET + \
     TECMO_ASSET_PACK_FINALE_REVERSE_PALETTE_COUNT * 16U)
#define TECMO_ASSET_PACK_FINALE_GROUPS_OFFSET \
    ((TECMO_ASSET_PACK_FINALE_REVERSE_PALETTE_FRAMES_OFFSET + \
      TECMO_ASSET_PACK_FINALE_REVERSE_PALETTE_COUNT * 2U + 3U) & ~3U)
#define TECMO_ASSET_PACK_FINALE_SPRITE_PALETTES_OFFSET \
    (TECMO_ASSET_PACK_FINALE_GROUPS_OFFSET + \
     TECMO_ASSET_PACK_FINALE_GROUP_COUNT * TECMO_ASSET_PACK_FINALE_GROUP_STRIDE)
#define TECMO_ASSET_PACK_FINALE_PIECES_OFFSET \
    (TECMO_ASSET_PACK_FINALE_SPRITE_PALETTES_OFFSET + \
     TECMO_ASSET_PACK_FINALE_GROUP_COUNT * 16U)
#define TECMO_ASSET_PACK_FINALE_ROUTES_OFFSET \
    (TECMO_ASSET_PACK_FINALE_PIECES_OFFSET + \
     TECMO_ASSET_PACK_FINALE_PIECE_COUNT * TECMO_ASSET_PACK_FINALE_PIECE_STRIDE)
#define TECMO_ASSET_PACK_FINALE_SHORT_ANCHORS_OFFSET \
    (TECMO_ASSET_PACK_FINALE_ROUTES_OFFSET + \
     TECMO_ASSET_PACK_FINALE_ROUTE_COUNT * TECMO_ASSET_PACK_FINALE_ROUTE_STRIDE)
#define TECMO_ASSET_PACK_FINALE_REVERSE_METADATA_OFFSET \
    ((TECMO_ASSET_PACK_FINALE_SHORT_ANCHORS_OFFSET + \
      TECMO_ASSET_PACK_FINALE_SHORT_ANCHOR_COUNT * TECMO_ASSET_PACK_FINALE_ANCHOR_STRIDE + 3U) & ~3U)
#define TECMO_ASSET_PACK_FINALE_TITLE_METADATA_OFFSET \
    (TECMO_ASSET_PACK_FINALE_REVERSE_METADATA_OFFSET + \
     TECMO_ASSET_PACK_FINALE_REVERSE_METADATA_SIZE)
#define TECMO_ASSET_PACK_FINALE_BANDS_OFFSET \
    (TECMO_ASSET_PACK_FINALE_TITLE_METADATA_OFFSET + \
     TECMO_ASSET_PACK_FINALE_TITLE_METADATA_SIZE)
#define TECMO_ASSET_PACK_FINALE_TITLE_SLOTS_OFFSET \
    (TECMO_ASSET_PACK_FINALE_BANDS_OFFSET + \
     TECMO_ASSET_PACK_FINALE_BAND_COUNT * TECMO_ASSET_PACK_FINALE_BAND_STRIDE)
#define TECMO_ASSET_PACK_FINALE_SIZE \
    (TECMO_ASSET_PACK_FINALE_TITLE_SLOTS_OFFSET + \
     TECMO_ASSET_PACK_FINALE_TITLE_SLOT_COUNT * TECMO_ASSET_PACK_FINALE_TITLE_SLOT_STRIDE)
#define TECMO_ASSET_PACK_FINALE_TITLE_SOURCE_CPU 0x836BU
#define TECMO_ASSET_PACK_FINALE_TITLE_SOURCE_SIZE 26U
#define TECMO_ASSET_PACK_FINALE_POINTER_TABLE_CPU 0xA90FU
#define TECMO_ASSET_PACK_FINALE_PIECE_STREAM_CPU 0xA9D2U
#define TECMO_ASSET_PACK_FINALE_SHORT_PALETTE_CPU 0x8A0DU
#define TECMO_ASSET_PACK_FINALE_REVERSE_PALETTE_CPU 0x89FDU
#define TECMO_ASSET_PACK_FINALE_SPECIAL_PALETTE_CPU 0x8A1DU
#define TECMO_ASSET_PACK_FINALE_GLYPH_MAP_CPU 0xA273U
#define TECMO_ASSET_PACK_FINALE_GLYPH_TABLE_CPU 0xAF05U
#define TECMO_ASSET_PACK_FINALE_FIXED_IRQ_CPU 0xFE14U
#define TECMO_ASSET_PACK_FINALE_FIXED_IRQ_SIZE 126U
#define TECMO_ASSET_PACK_FINALE_BANK04_FINGERPRINT_CPU 0x82CFU
#define TECMO_ASSET_PACK_FINALE_BANK04_FINGERPRINT_SIZE 913U
#define TECMO_ASSET_PACK_FINALE_BANK04_FINGERPRINT 0xFAEF1D02U
#define TECMO_ASSET_PACK_FINALE_DESCRIPTOR_FINGERPRINT_CPU 0xDC85U
#define TECMO_ASSET_PACK_FINALE_DESCRIPTOR_FINGERPRINT_SIZE 322U
#define TECMO_ASSET_PACK_FINALE_DESCRIPTOR_FINGERPRINT 0x66D469E1U
#define TECMO_ASSET_PACK_FINALE_IRQ_FINGERPRINT 0xE688E7F2U
#define TECMO_ASSET_PACK_FINALE_GEOMETRY_FINGERPRINT 0xE0B9063FU
#define TECMO_ASSET_PACK_FINALE_TITLE_HANDLER_CPU 0x9E50U
#define TECMO_ASSET_PACK_FINALE_TITLE_HANDLER_SIZE 90U
#define TECMO_ASSET_PACK_FINALE_TITLE_HANDLER_FINGERPRINT 0x9E459370U
#define TECMO_ASSET_PACK_FINALE_CHAR_MAP_FINGERPRINT_SIZE 91U
#define TECMO_ASSET_PACK_FINALE_CHAR_MAP_FINGERPRINT 0xC103E39DU

#define TECMO_ASSET_PACK_TITLE_WIDTH 32U
#define TECMO_ASSET_PACK_TITLE_HEIGHT 30U
#define TECMO_ASSET_PACK_TITLE_CELL_COUNT 960U
#define TECMO_ASSET_PACK_TITLE_CELL_STRIDE 6U
#define TECMO_ASSET_PACK_TITLE_SPRITE_COUNT 49U
#define TECMO_ASSET_PACK_TITLE_SPRITE_STRIDE 16U
#define TECMO_ASSET_PACK_TITLE_HEADER_SIZE 64U
#define TECMO_ASSET_PACK_TITLE_CELLS_OFFSET 64U
#define TECMO_ASSET_PACK_TITLE_PALETTE_OFFSET \
    (TECMO_ASSET_PACK_TITLE_CELLS_OFFSET + TECMO_ASSET_PACK_TITLE_CELL_COUNT * TECMO_ASSET_PACK_TITLE_CELL_STRIDE)
#define TECMO_ASSET_PACK_TITLE_ATTRACT_SPRITES_OFFSET (TECMO_ASSET_PACK_TITLE_PALETTE_OFFSET + 48U)
#define TECMO_ASSET_PACK_TITLE_ATTRACT_ATTRS_OFFSET \
    (TECMO_ASSET_PACK_TITLE_ATTRACT_SPRITES_OFFSET + TECMO_ASSET_PACK_TITLE_SPRITE_COUNT * TECMO_ASSET_PACK_TITLE_SPRITE_STRIDE)
#define TECMO_ASSET_PACK_TITLE_ATTRACT_SIZE (TECMO_ASSET_PACK_TITLE_ATTRACT_ATTRS_OFFSET + 32U)
#define TECMO_ASSET_PACK_TITLE_PROMPT_ROWS_OFFSET (TECMO_ASSET_PACK_TITLE_PALETTE_OFFSET + 16U)
#define TECMO_ASSET_PACK_TITLE_SCREEN_SIZE (TECMO_ASSET_PACK_TITLE_PROMPT_ROWS_OFFSET + 20U)

#define TECMO_ASSET_PACK_TITLE_ATTRACT_SCREEN_ID 1U
#define TECMO_ASSET_PACK_TITLE_START_SCREEN_ID 3U
#define TECMO_ASSET_PACK_TITLE_BG_R0 0xFEU
#define TECMO_ASSET_PACK_TITLE_BG_R1 0xFAU
#define TECMO_ASSET_PACK_TITLE_PALETTE_CPU 0x9366U
#define TECMO_ASSET_PACK_TITLE_ATTRACT_STREAM_CPU 0x861EU
#define TECMO_ASSET_PACK_TITLE_ATTRACT_STREAM_SIZE 209U
#define TECMO_ASSET_PACK_TITLE_START_STREAM_CPU 0x86EEU
#define TECMO_ASSET_PACK_TITLE_START_STREAM_SIZE 144U
#define TECMO_ASSET_PACK_TITLE_SPRITE_PALETTE_CPU 0xBE37U
#define TECMO_ASSET_PACK_TITLE_SPRITE_TABLE_CPU 0xAEEFU
#define TECMO_ASSET_PACK_TITLE_SPRITE_TABLE_SIZE 197U
#define TECMO_ASSET_PACK_TITLE_ATTR_A_CPU 0xBD60U
#define TECMO_ASSET_PACK_TITLE_ATTR_B_CPU 0xBD70U
#define TECMO_ASSET_PACK_TITLE_PROMPT_BLANK_CPU 0x80D0U
#define TECMO_ASSET_PACK_TITLE_PROMPT_VISIBLE_CPU 0x80DAU
#define TECMO_ASSET_PACK_TITLE_PROMPT_COUNT 10U

#define TECMO_ASSET_PACK_START_MENU_HEADER_SIZE 160U
#define TECMO_ASSET_PACK_START_MENU_WIDTH 32U
#define TECMO_ASSET_PACK_START_MENU_HEIGHT 30U
#define TECMO_ASSET_PACK_START_MENU_PAGE_COUNT 2U
#define TECMO_ASSET_PACK_START_MENU_CELL_STRIDE 6U
#define TECMO_ASSET_PACK_START_MENU_CELL_COUNT 1920U
#define TECMO_ASSET_PACK_START_MENU_CELLS_OFFSET TECMO_ASSET_PACK_START_MENU_HEADER_SIZE
#define TECMO_ASSET_PACK_START_MENU_PALETTE_STAGE_COUNT 9U
#define TECMO_ASSET_PACK_START_MENU_PALETTE_STRIDE 32U
#define TECMO_ASSET_PACK_START_MENU_PALETTES_OFFSET \
    (TECMO_ASSET_PACK_START_MENU_CELLS_OFFSET + \
     TECMO_ASSET_PACK_START_MENU_CELL_COUNT * TECMO_ASSET_PACK_START_MENU_CELL_STRIDE)
#define TECMO_ASSET_PACK_START_MENU_EMBLEM_COUNT 49U
#define TECMO_ASSET_PACK_START_MENU_SPRITE_STRIDE 16U
#define TECMO_ASSET_PACK_START_MENU_EMBLEM_OFFSET \
    (TECMO_ASSET_PACK_START_MENU_PALETTES_OFFSET + \
     TECMO_ASSET_PACK_START_MENU_PALETTE_STAGE_COUNT * \
         TECMO_ASSET_PACK_START_MENU_PALETTE_STRIDE)
#define TECMO_ASSET_PACK_START_MENU_CURSOR_OFFSET \
    (TECMO_ASSET_PACK_START_MENU_EMBLEM_OFFSET + \
     TECMO_ASSET_PACK_START_MENU_EMBLEM_COUNT * TECMO_ASSET_PACK_START_MENU_SPRITE_STRIDE)
#define TECMO_ASSET_PACK_START_MENU_OVERLAY_DESC_COUNT 3U
#define TECMO_ASSET_PACK_START_MENU_OVERLAY_DESC_STRIDE 16U
#define TECMO_ASSET_PACK_START_MENU_OVERLAY_DESCS_OFFSET \
    (TECMO_ASSET_PACK_START_MENU_CURSOR_OFFSET + TECMO_ASSET_PACK_START_MENU_SPRITE_STRIDE)
#define TECMO_ASSET_PACK_START_MENU_OVERLAY_CELL_COUNT (42U + 80U + 84U)
#define TECMO_ASSET_PACK_START_MENU_OVERLAY_CELLS_OFFSET \
    (TECMO_ASSET_PACK_START_MENU_OVERLAY_DESCS_OFFSET + \
     TECMO_ASSET_PACK_START_MENU_OVERLAY_DESC_COUNT * \
         TECMO_ASSET_PACK_START_MENU_OVERLAY_DESC_STRIDE)
#define TECMO_ASSET_PACK_START_MENU_DIGIT_COUNT 10U
#define TECMO_ASSET_PACK_START_MENU_DIGITS_OFFSET \
    (TECMO_ASSET_PACK_START_MENU_OVERLAY_CELLS_OFFSET + \
     TECMO_ASSET_PACK_START_MENU_OVERLAY_CELL_COUNT * \
         TECMO_ASSET_PACK_START_MENU_CELL_STRIDE)
#define TECMO_ASSET_PACK_START_MENU_SIZE \
    (TECMO_ASSET_PACK_START_MENU_DIGITS_OFFSET + \
     TECMO_ASSET_PACK_START_MENU_DIGIT_COUNT * TECMO_ASSET_PACK_START_MENU_CELL_STRIDE)
#define TECMO_ASSET_PACK_START_MENU_SCREEN_ID 4U
#define TECMO_ASSET_PACK_START_MENU_DESCRIPTOR_CPU 0xDCA1U
#define TECMO_ASSET_PACK_START_MENU_STREAM_CPU 0x8898U
#define TECMO_ASSET_PACK_START_MENU_STREAM_SIZE 220U
#define TECMO_ASSET_PACK_START_MENU_BG_PALETTE_CPU 0x9356U
#define TECMO_ASSET_PACK_START_MENU_TITLE_BG_PALETTE_CPU 0x9366U
#define TECMO_ASSET_PACK_START_MENU_TITLE_SPRITE_PALETTE_CPU 0xBE27U
#define TECMO_ASSET_PACK_START_MENU_SPRITE_SETUP_CPU 0xBD84U
#define TECMO_ASSET_PACK_START_MENU_SPRITE_PALETTE_CPU 0xBE37U
#define TECMO_ASSET_PACK_START_MENU_EMBLEM_CPU 0xAEEFU
#define TECMO_ASSET_PACK_START_MENU_CURSOR_CPU 0x8031U
#define TECMO_ASSET_PACK_START_MENU_CHAR_MAP_CPU 0x9AA8U
#define TECMO_ASSET_PACK_START_MENU_MAIN_RECORD_CPU 0x9B55U
#define TECMO_ASSET_PACK_START_MENU_MAIN_RECORD_SIZE 110U
#define TECMO_ASSET_PACK_START_MENU_MUSIC_RECORD_CPU 0x9BC3U
#define TECMO_ASSET_PACK_START_MENU_MUSIC_RECORD_SIZE 21U
#define TECMO_ASSET_PACK_START_MENU_SPEED_RECORD_CPU 0x9BD8U
#define TECMO_ASSET_PACK_START_MENU_SPEED_RECORD_SIZE 33U
#define TECMO_ASSET_PACK_START_MENU_SEASON_RECORD_CPU 0x9BF9U
#define TECMO_ASSET_PACK_START_MENU_SEASON_RECORD_SIZE 101U
#define TECMO_ASSET_PACK_START_MENU_PERIOD_RECORD_CPU 0x9CFDU
#define TECMO_ASSET_PACK_START_MENU_PERIOD_RECORD_SIZE 37U
#define TECMO_ASSET_PACK_START_MENU_PERIOD_VALUES_CPU 0x8374U
#define TECMO_ASSET_PACK_START_MENU_PERIOD_VALUE_COUNT 5U
#define TECMO_ASSET_PACK_START_MENU_PERIOD_VALUES_HEADER_OFFSET 121U
#define TECMO_ASSET_PACK_START_MENU_INPUT_GATE_SEED_HEADER_OFFSET 126U
#define TECMO_ASSET_PACK_START_MENU_PERIOD_SETUP_EXTRA_HEADER_OFFSET 127U
#define TECMO_ASSET_PACK_START_MENU_EXIT_PALETTE_STEP_HEADER_OFFSET 128U
#define TECMO_ASSET_PACK_START_MENU_EXIT_BLACK_FRAME_HEADER_OFFSET 129U
#define TECMO_ASSET_PACK_START_MENU_EXIT_DISPATCH_FRAME_HEADER_OFFSET 130U
#define TECMO_ASSET_PACK_START_MENU_ROOT_INPUT_MASK_HEADER_OFFSET 131U
#define TECMO_ASSET_PACK_START_MENU_GENERIC_INPUT_MASK_HEADER_OFFSET 132U
#define TECMO_ASSET_PACK_START_MENU_PERIOD_INPUT_MASK_HEADER_OFFSET 133U
#define TECMO_ASSET_PACK_START_MENU_DIRECTION_MASK_HEADER_OFFSET 134U
#define TECMO_ASSET_PACK_START_MENU_INITIAL_GATE_HEADER_OFFSET 135U
#define TECMO_ASSET_PACK_START_MENU_ROW_CADENCE_HEADER_OFFSET 136U
#define TECMO_ASSET_PACK_START_MENU_SETUP_ROW_START_HEADER_OFFSET 137U
#define TECMO_ASSET_PACK_START_MENU_TEARDOWN_ROW_START_HEADER_OFFSET 138U
#define TECMO_ASSET_PACK_START_MENU_METADATA_ALIGNMENT_HEADER_OFFSET 139U
#define TECMO_ASSET_PACK_START_MENU_CHR_SIZE_HEADER_OFFSET 140U
#define TECMO_ASSET_PACK_START_MENU_CHR_FNV1A32_HEADER_OFFSET 144U
#define TECMO_ASSET_PACK_START_MENU_CURSOR_COMMIT_DELAY_HEADER_OFFSET 148U
#define TECMO_ASSET_PACK_START_MENU_MUSIC_CURSOR_X_HEADER_OFFSET 149U
#define TECMO_ASSET_PACK_START_MENU_MUSIC_CURSOR_Y_HEADER_OFFSET 150U
#define TECMO_ASSET_PACK_START_MENU_SPEED_CURSOR_X_HEADER_OFFSET 151U
#define TECMO_ASSET_PACK_START_MENU_SPEED_CURSOR_Y_HEADER_OFFSET 152U
#define TECMO_ASSET_PACK_START_MENU_PERIOD_CURSOR_X_HEADER_OFFSET 153U
#define TECMO_ASSET_PACK_START_MENU_PERIOD_CURSOR_Y_HEADER_OFFSET 154U
#define TECMO_ASSET_PACK_START_MENU_METADATA_RESERVED_HEADER_OFFSET 155U
#define TECMO_ASSET_PACK_START_MENU_REV1_CHR_SIZE 262144U
#define TECMO_ASSET_PACK_START_MENU_REV1_CHR_FNV1A32 0xF6F6E854U
#define TECMO_ASSET_PACK_START_MENU_LOADER_CPU 0xD92BU
#define TECMO_ASSET_PACK_START_MENU_LOADER_SIZE 122U
#define TECMO_ASSET_PACK_START_MENU_FADE_OUT_CPU 0xDB25U
#define TECMO_ASSET_PACK_START_MENU_FADE_OUT_SIZE 99U
#define TECMO_ASSET_PACK_START_MENU_FADE_IN_CPU 0xDB88U
#define TECMO_ASSET_PACK_START_MENU_FADE_IN_SIZE 72U
#define TECMO_ASSET_PACK_START_MENU_SEASON_ROUTE_CPU 0x8379U
#define TECMO_ASSET_PACK_START_MENU_SEASON_ROUTE_SIZE 161U
#define TECMO_ASSET_PACK_START_MENU_INPUT_PARAMS_CPU 0x9F13U
#define TECMO_ASSET_PACK_START_MENU_INPUT_PARAMS_SIZE 145U
#define TECMO_ASSET_PACK_START_MENU_POINTER_COORD_CPU 0x9FA4U
#define TECMO_ASSET_PACK_START_MENU_POINTER_COORD_SIZE 247U
#define TECMO_ASSET_PACK_START_MENU_MUSIC_FLOW_CPU 0x81C6U
#define TECMO_ASSET_PACK_START_MENU_MUSIC_FLOW_SIZE 44U
#define TECMO_ASSET_PACK_START_MENU_SPEED_FLOW_CPU 0x81F2U
#define TECMO_ASSET_PACK_START_MENU_SPEED_FLOW_SIZE 47U
#define TECMO_ASSET_PACK_START_MENU_PERIOD_FLOW_CPU 0x82ECU
#define TECMO_ASSET_PACK_START_MENU_PERIOD_FLOW_SIZE 136U
#define TECMO_ASSET_PACK_START_MENU_OVERLAY_TRANSFER_CPU 0x9A24U
#define TECMO_ASSET_PACK_START_MENU_OVERLAY_TRANSFER_SIZE 164U
#define TECMO_ASSET_PACK_START_MENU_RECORD_RENDER_CPU 0xAB06U
#define TECMO_ASSET_PACK_START_MENU_RECORD_RENDER_SIZE 517U
#define TECMO_ASSET_PACK_START_MENU_INPUT_WRAPPER_CPU 0x9EC6U
#define TECMO_ASSET_PACK_START_MENU_INPUT_WRAPPER_SIZE 77U
#define TECMO_ASSET_PACK_START_MENU_CONTROLLER_POLL_CPU 0xD317U
#define TECMO_ASSET_PACK_START_MENU_CONTROLLER_POLL_SIZE 9U
#define TECMO_ASSET_PACK_START_MENU_INPUT_HELPER_CPU 0xD723U
#define TECMO_ASSET_PACK_START_MENU_INPUT_HELPER_SIZE 273U
#define TECMO_ASSET_PACK_START_MENU_TITLE_CALL_AND_MENU_SESSION_SETUP_CPU 0xE455U
#define TECMO_ASSET_PACK_START_MENU_TITLE_CALL_AND_MENU_SESSION_SETUP_SIZE 44U
#define TECMO_ASSET_PACK_START_MENU_CALL_AND_POST_RETURN_EXIT_CHAIN_CPU 0xE481U
#define TECMO_ASSET_PACK_START_MENU_CALL_AND_POST_RETURN_EXIT_CHAIN_SIZE 41U

#define TECMO_ASSET_PACK_PRESEASON_HEADER_SIZE 256U
#define TECMO_ASSET_PACK_PRESEASON_OVERLAY_COUNT 3U
#define TECMO_ASSET_PACK_PRESEASON_OVERLAY_DESC_STRIDE 16U
#define TECMO_ASSET_PACK_PRESEASON_OVERLAY_DESCS_OFFSET TECMO_ASSET_PACK_PRESEASON_HEADER_SIZE
#define TECMO_ASSET_PACK_PRESEASON_OVERLAY_CELL_COUNT (210U + 196U + 104U)
#define TECMO_ASSET_PACK_PRESEASON_CELL_STRIDE 6U
#define TECMO_ASSET_PACK_PRESEASON_OVERLAY_CELLS_OFFSET \
    (TECMO_ASSET_PACK_PRESEASON_OVERLAY_DESCS_OFFSET + \
     TECMO_ASSET_PACK_PRESEASON_OVERLAY_COUNT * \
         TECMO_ASSET_PACK_PRESEASON_OVERLAY_DESC_STRIDE)
#define TECMO_ASSET_PACK_PRESEASON_TEAM_SCREEN_COUNT 4U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_CELL_COUNT \
    (TECMO_ASSET_PACK_PRESEASON_TEAM_SCREEN_COUNT * 960U)
#define TECMO_ASSET_PACK_PRESEASON_TEAM_CELLS_OFFSET \
    (TECMO_ASSET_PACK_PRESEASON_OVERLAY_CELLS_OFFSET + \
     TECMO_ASSET_PACK_PRESEASON_OVERLAY_CELL_COUNT * \
         TECMO_ASSET_PACK_PRESEASON_CELL_STRIDE)
#define TECMO_ASSET_PACK_PRESEASON_TEAM_PALETTES_OFFSET \
    (TECMO_ASSET_PACK_PRESEASON_TEAM_CELLS_OFFSET + \
     TECMO_ASSET_PACK_PRESEASON_TEAM_CELL_COUNT * \
         TECMO_ASSET_PACK_PRESEASON_CELL_STRIDE)
#define TECMO_ASSET_PACK_PRESEASON_MARKER_PIECE_COUNT 10U
#define TECMO_ASSET_PACK_PRESEASON_MARKER_STRIDE 16U
#define TECMO_ASSET_PACK_PRESEASON_MARKERS_OFFSET \
    (TECMO_ASSET_PACK_PRESEASON_TEAM_PALETTES_OFFSET + \
     TECMO_ASSET_PACK_PRESEASON_TEAM_SCREEN_COUNT * 16U)
#define TECMO_ASSET_PACK_PRESEASON_TEAM_COUNT 27U
#define TECMO_ASSET_PACK_PRESEASON_COORDS_OFFSET \
    (TECMO_ASSET_PACK_PRESEASON_MARKERS_OFFSET + \
     TECMO_ASSET_PACK_PRESEASON_MARKER_PIECE_COUNT * \
         TECMO_ASSET_PACK_PRESEASON_MARKER_STRIDE)
#define TECMO_ASSET_PACK_PRESEASON_DIVISION_OFFSETS_OFFSET \
    (TECMO_ASSET_PACK_PRESEASON_COORDS_OFFSET + \
     TECMO_ASSET_PACK_PRESEASON_TEAM_COUNT * 2U)
#define TECMO_ASSET_PACK_PRESEASON_DIVISION_COUNTS_OFFSET \
    (TECMO_ASSET_PACK_PRESEASON_DIVISION_OFFSETS_OFFSET + 4U)
#define TECMO_ASSET_PACK_PRESEASON_TEAM_IDS_OFFSET \
    (TECMO_ASSET_PACK_PRESEASON_DIVISION_COUNTS_OFFSET + 4U)
#define TECMO_ASSET_PACK_PRESEASON_OWNERSHIP_OFFSET \
    (TECMO_ASSET_PACK_PRESEASON_TEAM_IDS_OFFSET + \
     TECMO_ASSET_PACK_PRESEASON_TEAM_COUNT)
#define TECMO_ASSET_PACK_PRESEASON_CONFIGS_OFFSET \
    (TECMO_ASSET_PACK_PRESEASON_OWNERSHIP_OFFSET + 12U)
#define TECMO_ASSET_PACK_PRESEASON_SIZE \
    (TECMO_ASSET_PACK_PRESEASON_CONFIGS_OFFSET + 7U)
#define TECMO_ASSET_PACK_PRESEASON_FNV1A32 0xD9EE49F4U

#define TECMO_ASSET_PACK_PRESEASON_CONTROL_RECORD_CPU 0x9C5EU
#define TECMO_ASSET_PACK_PRESEASON_CONTROL_RECORD_SIZE 91U
#define TECMO_ASSET_PACK_PRESEASON_DIVISION_RECORD_CPU 0x9CB9U
#define TECMO_ASSET_PACK_PRESEASON_DIVISION_RECORD_SIZE 68U
#define TECMO_ASSET_PACK_PRESEASON_DIFFICULTY_RECORD_CPU 0x9D22U
#define TECMO_ASSET_PACK_PRESEASON_DIFFICULTY_RECORD_SIZE 40U
#define TECMO_ASSET_PACK_PRESEASON_ROOT_VECTOR_CPU 0x81B8U
#define TECMO_ASSET_PACK_PRESEASON_ROOT_VECTOR_SIZE 14U
#define TECMO_ASSET_PACK_PRESEASON_FLOW_CPU 0x9966U
#define TECMO_ASSET_PACK_PRESEASON_FLOW_SIZE 116U
#define TECMO_ASSET_PACK_PRESEASON_OWNERSHIP_CPU 0x99DAU
#define TECMO_ASSET_PACK_PRESEASON_OWNERSHIP_SIZE 12U
#define TECMO_ASSET_PACK_PRESEASON_DIFFICULTY_FLOW_CPU 0x99E6U
#define TECMO_ASSET_PACK_PRESEASON_DIFFICULTY_FLOW_SIZE 62U
#define TECMO_ASSET_PACK_PRESEASON_INPUT_COORD_POINTERS_CPU 0x9FA4U
#define TECMO_ASSET_PACK_PRESEASON_INPUT_COORD_POINTERS_SIZE 116U
#define TECMO_ASSET_PACK_PRESEASON_COORD_TABLES_CPU 0xA018U
#define TECMO_ASSET_PACK_PRESEASON_COORD_TABLES_SIZE 131U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_DRIVER_CPU 0xB1CCU
#define TECMO_ASSET_PACK_PRESEASON_TEAM_DRIVER_SIZE 167U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_MAPS_CPU 0xB273U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_MAPS_SIZE 47U
#define TECMO_ASSET_PACK_PRESEASON_DIVISION_OFFSETS_CPU 0xB283U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_IDS_CPU 0xB287U
#define TECMO_ASSET_PACK_PRESEASON_MARKERS_CPU 0x8036U
#define TECMO_ASSET_PACK_PRESEASON_MARKERS_SIZE 20U
#define TECMO_ASSET_PACK_PRESEASON_DESCRIPTOR_CPU 0xDCAFU
#define TECMO_ASSET_PACK_PRESEASON_DESCRIPTOR_SIZE 28U
#define TECMO_ASSET_PACK_PRESEASON_PALETTE_CPU 0x9386U
#define TECMO_ASSET_PACK_PRESEASON_PALETTE_SIZE 64U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_ENTRY_FRAMES 16U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_PALETTE_FULL_FRAMES 31U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_FIRST_VISIBLE_FRAME 18U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_PALETTE_STEP_FRAMES 4U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_VISIBLE_FULL_FRAME 30U
#define TECMO_ASSET_PACK_PRESEASON_RETURN_FIRST_VISIBLE_FRAME 1U
#define TECMO_ASSET_PACK_PRESEASON_RETURN_PALETTE_STEP_FRAMES 4U
#define TECMO_ASSET_PACK_PRESEASON_RETURN_VISIBLE_FULL_FRAME 13U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_ENTRY_STAGE7_FRAME 3U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_ENTRY_STAGE6_FRAME 5U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_ENTRY_STAGE5_FRAME 7U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_ENTRY_BLACK_FRAME 9U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_EXIT_CAP2_FRAME 1U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_EXIT_CAP1_FRAME 3U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_EXIT_CAP0_FRAME 5U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_EXIT_BLACK_FRAME 7U
#define TECMO_ASSET_PACK_PRESEASON_TEAM_EXIT_FRAMES 32U
#define TECMO_ASSET_PACK_PRESEASON_CHR_SIZE 262144U
#define TECMO_ASSET_PACK_PRESEASON_CHR_FNV1A32 0xF6F6E854U
#define TECMO_ASSET_PACK_PRESEASON_TSGM_SIZE 14112U
#define TECMO_ASSET_PACK_PRESEASON_TSGM_FNV1A32 0xDF89006BU

typedef struct TecmoArenaBackgroundProvenance {
    uint32_t route_bank;
    uint32_t route_cpu;
    uint64_t route_source_offset;
    uint32_t descriptor_bank;
    uint32_t descriptor_cpu;
    uint64_t descriptor_source_offset;
    uint32_t stream_bank;
    uint32_t stream_cpu;
    uint64_t stream_source_offset;
    uint64_t stream_encoded_size;
    uint32_t palette_cpu;
    uint64_t palette_source_offset;
    uint64_t lower_r0_table_source_offset;
    uint64_t lower_r1_table_source_offset;
} TecmoArenaBackgroundProvenance;

typedef struct TecmoArenaSpriteGroupsProvenance {
    uint64_t palette_source_offset;
    uint64_t pointer_table_source_offset;
    uint32_t stream_cpu[2];
    uint64_t stream_source_offset[2];
    uint32_t stream_size[2];
    uint64_t seeds_source_offset;
    uint64_t emitter_source_offset;
    uint64_t params_source_offset;
    uint64_t chr_page_source_offset[2];
} TecmoArenaSpriteGroupsProvenance;

typedef struct TecmoPostArenaProvenance {
    uint64_t ready_route_offset;
    uint64_t ready_descriptor_offset;
    uint64_t ready_stream_offset;
    uint64_t ready_stream_size;
    uint64_t ready_palette_offset;
    uint64_t ready_script_offset;
    uint64_t warriors_route_offset;
    uint64_t warriors_descriptor_offset;
    uint64_t warriors_stream_offset;
    uint64_t warriors_stream_size;
    uint64_t warriors_palette_offset;
    uint64_t warriors_sprite_palette_offset;
    uint64_t warriors_pointer_offset;
    uint64_t warriors_piece_stream_offset;
    uint64_t warriors_patch_offset[2];
    uint64_t warriors_wordmark_glyph_offset[TECMO_ASSET_PACK_WARRIORS_WORDMARK_GLYPH_COUNT];
    uint64_t clippers_route_offset;
    uint64_t clippers_descriptor_offset;
    uint64_t clippers_stream_offset;
    uint64_t clippers_stream_size;
    uint64_t clippers_palette_offset;
    uint64_t clippers_irq_table_offset[2];
    uint64_t clippers_string_offset;
    uint64_t clippers_glyph_table_offset;
    uint64_t bucks_route_offset;
    uint64_t bucks_descriptor_offset;
    uint64_t bucks_stream_offset;
    uint64_t bucks_stream_size;
    uint64_t bucks_palette_offset;
    uint64_t bucks_threshold_offset;
    uint64_t bucks_string_offset;
    uint64_t bucks_glyph_table_offset;
    uint64_t pass_route_offset;
    uint64_t pass_descriptor_offset;
    uint64_t pass_stream_offset;
    uint64_t pass_stream_size;
    uint64_t pass_palette_offset;
    uint64_t pass_helper_palette_offset;
    uint64_t pass_special_palette_offset;
    uint64_t pass_pointer_offset;
    uint64_t pass_piece_stream_offset;
} TecmoPostArenaProvenance;

typedef struct TecmoFinaleScreenProvenance {
    uint64_t descriptor_offset;
    uint64_t stream_offset;
    uint64_t stream_size;
    uint64_t palette_offset;
    uint32_t stream_bank;
    uint32_t stream_cpu;
    uint32_t palette_cpu;
} TecmoFinaleScreenProvenance;

typedef struct TecmoFinaleProvenance {
    uint64_t dispatch_offset;
    TecmoFinaleScreenProvenance screens[TECMO_ASSET_PACK_FINALE_SCREEN_COUNT];
    uint64_t route_offsets[TECMO_ASSET_PACK_FINALE_ROUTE_COUNT];
    uint64_t short_anchor_table_offset;
    uint64_t reverse_selector_offset;
    uint64_t reverse_indexed_operand_offset[4];
    uint64_t sprite_pointer_offset;
    uint64_t sprite_stream_offset;
    uint64_t sprite_palette_offset[TECMO_ASSET_PACK_FINALE_GROUP_COUNT];
    uint64_t sprite_chr_selector_offset[3];
    uint8_t sprite_chr_selector[3];
    uint64_t title_code_offset;
    uint64_t title_source_offset;
    uint64_t glyph_map_offset;
    uint64_t glyph_table_offset;
    uint64_t fixed_irq_offset;
} TecmoFinaleProvenance;

typedef struct TecmoOpeningScreenProvenance {
    uint8_t screen_id;
    uint8_t bg_r0;
    uint8_t bg_r1;
    uint32_t stream_cpu;
    uint32_t palette_cpu;
    uint64_t descriptor_offset;
    uint64_t stream_offset;
    uint64_t stream_size;
    uint64_t palette_offset;
    uint64_t selector_code_offset;
    uint64_t sprite_table_offset;
    uint64_t sprite_palette_offset;
    uint64_t y_base_operand_offset;
    uint64_t tile_base_operand_offset;
    uint64_t x_base_operand_offset;
} TecmoOpeningScreenProvenance;

typedef struct TecmoTitleProvenance {
    uint64_t descriptor_offset;
    uint64_t stream_offset;
    uint64_t stream_size;
    uint64_t palette_offset;
    uint64_t sprite_palette_offset;
    uint64_t sprite_table_offset;
    uint64_t attr_a_offset;
    uint64_t attr_b_offset;
    uint64_t prompt_blank_offset;
    uint64_t prompt_visible_offset;
    uint32_t stream_cpu;
    uint8_t screen_id;
} TecmoTitleProvenance;

typedef struct TecmoStartGameMenuProvenance {
    uint64_t chr_offset;
    uint64_t descriptor_offset;
    uint64_t stream_offset;
    uint64_t stream_size;
    uint64_t background_palette_offset;
    uint64_t title_background_palette_offset;
    uint64_t title_sprite_palette_offset;
    uint64_t sprite_setup_offset;
    uint64_t sprite_palette_offset;
    uint64_t emblem_offset;
    uint64_t cursor_offset;
    uint64_t char_map_offset;
    uint64_t main_record_offset;
    uint64_t season_record_offset;
    uint64_t music_record_offset;
    uint64_t speed_record_offset;
    uint64_t period_record_offset;
    uint64_t period_values_offset;
    uint64_t loader_offset;
    uint64_t fade_out_offset;
    uint64_t fade_in_offset;
    uint64_t season_route_offset;
    uint64_t input_params_offset;
    uint64_t pointer_coord_offset;
    uint64_t music_flow_offset;
    uint64_t speed_flow_offset;
    uint64_t period_flow_offset;
    uint64_t overlay_transfer_offset;
    uint64_t record_render_offset;
    uint64_t input_wrapper_offset;
    uint64_t controller_poll_offset;
    uint64_t input_helper_offset;
    uint64_t title_call_and_menu_session_setup_offset;
    uint64_t start_menu_call_and_post_return_exit_chain_offset;
} TecmoStartGameMenuProvenance;

typedef struct TecmoPreseasonMenuProvenance {
    uint64_t chr_offset;
    uint64_t base_descriptor_offset;
    uint64_t base_stream_offset;
    uint64_t base_stream_size;
    uint64_t root_vector_offset;
    uint64_t flow_offset;
    uint64_t ownership_offset;
    uint64_t difficulty_flow_offset;
    uint64_t popup_builder_offset;
    uint64_t char_map_offset;
    uint64_t control_record_offset;
    uint64_t division_record_offset;
    uint64_t difficulty_record_offset;
    uint64_t input_wrapper_offset;
    uint64_t input_params_offset;
    uint64_t input_coord_pointers_offset;
    uint64_t coord_tables_offset;
    uint64_t team_driver_offset;
    uint64_t team_maps_offset;
    uint64_t marker_records_offset;
    uint64_t cursor_record_offset;
    uint64_t descriptor_offsets[4];
    uint64_t stream_offsets[4];
    uint64_t stream_sizes[4];
    uint64_t palette_offsets[4];
    uint64_t controller_poll_offset;
    uint64_t input_helper_offset;
    uint64_t screen_loader_offset;
    uint64_t fade_out_offset;
    uint64_t fade_in_offset;
    uint64_t post_return_exit_chain_offset;
} TecmoPreseasonMenuProvenance;

#endif
