#ifndef TECMO_ASSET_PACK_GAMEPLAY_DUNK_CUTAWAY_H
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_CUTAWAY_H

#include "tecmo_gameplay_dunk_cutaway.h"

#include <stddef.h>
#include <stdint.h>

#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_ID "gameplay/dunk-cutaway"
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_VERSION 1U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_HEADER_SIZE 256U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_SOURCE_STRIDE 32U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_SOURCES_OFFSET 256U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_RAW_OFFSET 832U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_RAW_SIZE 3929U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_PADDING_OFFSET 4761U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_PADDING_SIZE 7U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_CELLS_OFFSET 4768U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_CELL_STRIDE 8U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_PALETTE_OFFSET 20128U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_PALETTE_SIZE 32U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_STAGES_OFFSET 20160U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_STAGE_STRIDE 16U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_SIZE 20272U

#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_CHR_SIZE 262144U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_CHR_FNV1A32 0xF6F6E854U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_CHR_FNV1A64 0x96A64F53B240ABB4ULL
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_DECODED_FNV1A32 0x5414E3B6U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_PAGE0_FNV1A32 0xBA33539BU
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_PAGE1_FNV1A32 0x7DF03FACU
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_BASE_PALETTE_FNV1A32 0xDEFFF0C1U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_REFERENCE_BG_FNV1A32 0xDC2F67E5U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_REFERENCE_SPRITE_FNV1A32 0x7E958A9EU
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_REFERENCE_PALETTE_FNV1A32 0x939EBCBEU
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_POINTERS_FNV1A32 0xC5920587U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_POINTER_ONLY_FNV1A32 0x186770F1U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_GEOMETRY_FNV1A32 0xD9F05A73U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_POINTER_GEOMETRY_FNV1A32 0x44A89FCDU
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_SIDE0_CHR_FNV1A32 0xD53134C7U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_SIDE1_BG_CHR_FNV1A32 0xDADB0DF0U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_STAGE0_CHR_FNV1A32 0x35B498B8U
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_STAGE1_CHR_FNV1A32 0xA2E432DFU
#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_STAGE2_CHR_FNV1A32 0xE5173F95U

#define TECMO_ASSET_PACK_GAMEPLAY_DUNK_FNV1A32 0xE02F2D21U

typedef struct TecmoGameplayDunkExpectedSource {
    TecmoGameplayDunkSourceKind kind;
    uint8_t bank;
    uint8_t fixed_bank;
    uint16_t cpu_start;
    uint32_t byte_count;
    uint32_t payload_offset;
    uint32_t fingerprint;
} TecmoGameplayDunkExpectedSource;

typedef struct TecmoGameplayDunkProvenance {
    uint64_t source_offsets[TECMO_GAMEPLAY_DUNK_SOURCE_COUNT];
    uint64_t chr_offset;
} TecmoGameplayDunkProvenance;

extern const TecmoGameplayDunkExpectedSource
    tecmo_gameplay_dunk_expected_sources[TECMO_GAMEPLAY_DUNK_SOURCE_COUNT];

int tecmo_asset_pack_build_gameplay_dunk_cutaway(
    const uint8_t *rom,
    uint64_t rom_size,
    uint64_t prg_offset,
    uint32_t prg_banks,
    uint64_t chr_offset,
    uint64_t chr_size,
    int enforce_revision_fingerprints,
    uint8_t *payload,
    size_t payload_size,
    TecmoGameplayDunkProvenance *provenance,
    char *message,
    size_t message_size);

int tecmo_asset_pack_gameplay_dunk_cutaway_self_test(char *message,
                                                      size_t message_size);

#endif
