#ifndef TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_H
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_H

#include "tecmo_gameplay_cpu_steering.h"

#include <stddef.h>
#include <stdint.h>

#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_ID \
    "gameplay/cpu-steering"
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_VERSION 1U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_HEADER_SIZE 320U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_SOURCE_STRIDE 32U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_SOURCES_OFFSET 320U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_DESCRIPTOR_OFFSET 96U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_DESCRIPTOR_STRIDE 12U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_HANDLER_OFFSET 216U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_DIRECTION_OFFSET 88U

#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_ACTOR_DISPATCH_OFFSET 640U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_ACTOR_DISPATCH_SIZE 221U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_REFERENCE_DIRECTION_OFFSET 864U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_REFERENCE_DIRECTION_SIZE 258U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_TARGET_DIRECTION_OFFSET 1136U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_TARGET_DIRECTION_SIZE 444U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_DISPATCH_OFFSET 1584U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_DISPATCH_SIZE 81U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_HANDLERS_OFFSET 1680U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_HANDLERS_SIZE 1623U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_TARGET_APPLY_OFFSET 3312U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_TARGET_APPLY_SIZE 170U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_FORMATION_STREAM_OFFSET 3488U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_FORMATION_STREAM_SIZE 662U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_TRAMPOLINE_OFFSET 4160U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_TRAMPOLINE_SIZE 3U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_READER_OFFSET 4176U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_READER_SIZE 23U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_PLAY_COMMANDS_OFFSET 4208U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_PLAY_COMMANDS_SIZE 3400U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_SIZE 7616U

#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_ACTOR_DISPATCH_FNV1A32 \
    0x23BB7271U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_REFERENCE_DIRECTION_FNV1A32 \
    0xF866B06CU
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_TARGET_DIRECTION_FNV1A32 \
    0x9616E586U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_DISPATCH_FNV1A32 \
    0x9AD2BA91U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_HANDLERS_FNV1A32 \
    0x344298FEU
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_TARGET_APPLY_FNV1A32 \
    0xC82E6853U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_FORMATION_STREAM_FNV1A32 \
    0x47818A62U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_TRAMPOLINE_FNV1A32 \
    0x14B2472EU
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_READER_FNV1A32 \
    0x41C5B5C8U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_PLAY_COMMANDS_FNV1A32 \
    0x71331A96U

#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_FNV1A32 0xD6C4DB35U

typedef struct TecmoGameplayCpuSteeringExpectedSource {
    TecmoGameplayCpuSteeringSourceKind kind;
    uint8_t bank;
    uint8_t fixed_bank;
    uint16_t cpu_start;
    uint32_t byte_count;
    uint32_t fingerprint;
    uint32_t payload_offset;
} TecmoGameplayCpuSteeringExpectedSource;

typedef struct TecmoGameplayCpuSteeringProvenance {
    uint64_t source_offsets[TECMO_GAMEPLAY_CPU_STEERING_SOURCE_COUNT];
} TecmoGameplayCpuSteeringProvenance;

extern const TecmoGameplayCpuSteeringExpectedSource
    tecmo_gameplay_cpu_steering_expected_sources[
        TECMO_GAMEPLAY_CPU_STEERING_SOURCE_COUNT];

int tecmo_asset_pack_build_gameplay_cpu_steering(
    const uint8_t *rom,
    uint64_t rom_size,
    uint64_t prg_offset,
    uint32_t prg_banks,
    int enforce_revision_fingerprints,
    uint8_t *payload,
    size_t payload_size,
    TecmoGameplayCpuSteeringProvenance *provenance,
    char *message,
    size_t message_size);
int tecmo_asset_pack_gameplay_cpu_steering_source_test(
    const char *rom_path,
    char *message,
    size_t message_size);
int tecmo_asset_pack_gameplay_cpu_steering_self_test(
    char *message,
    size_t message_size);

#endif
