#ifndef TECMO_ASSET_PACK_GAMEPLAY_CAMERA_H
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_H

#include "tecmo_gameplay_camera.h"

#include <stddef.h>
#include <stdint.h>

#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_ID "gameplay/camera-projection"
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_VERSION 2U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_HEADER_SIZE 256U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_SOURCE_STRIDE 32U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_SOURCES_OFFSET 256U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_HEADER_DESCRIPTOR_OFFSET 76U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_HEADER_DESCRIPTOR_STRIDE 12U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_INITIAL_CAMERA_X_OFFSET 160U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_INITIAL_SCROLL_X_OFFSET 162U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_INITIAL_SCROLL_AUX_OFFSET 163U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_INITIAL_PAGE_OFFSET 164U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_INITIAL_AUX_OFFSET 165U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_INITIAL_DIRECTION_OFFSET 166U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_INITIAL_CURSOR_OFFSET 167U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_ENDPOINT_SPEED_OFFSET 168U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_GENERIC_SPEED_OFFSET 169U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_SETTLE_LIMIT_OFFSET 170U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_WORLD_X_WIDTH_OFFSET 172U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_WORLD_Y_WIDTH_OFFSET 173U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_VISIBLE_HIGH_OFFSET 174U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_Y_SATURATES_OFFSET 175U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_THRESHOLDS_OFFSET 176U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_PRE_SHA_RESERVED_OFFSET 182U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_ACTOR_CLAMP_SHA256_OFFSET 184U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_HEADER_RESERVED_OFFSET 216U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_INITIALIZE_OFFSET 480U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_INITIALIZE_SIZE 26U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_STREAM_OFFSET 512U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_STREAM_SIZE 251U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_ATTRIBUTE_OFFSET 768U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_ATTRIBUTE_SIZE 85U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_FOLLOW_OFFSET 864U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_FOLLOW_SIZE 383U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_SETTLE_OFFSET 1248U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_SETTLE_SIZE 62U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_PROJECTION_OFFSET 1312U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_PROJECTION_SIZE 39U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_ACTOR_CLAMP_OFFSET 1360U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_ACTOR_CLAMP_SIZE 171U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_SIZE 1536U

#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_INITIALIZE_FNV1A32 0xA5CF7665U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_STREAM_FNV1A32 0x7BC5351DU
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_ATTRIBUTE_FNV1A32 0x7FE800D4U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_FOLLOW_FNV1A32 0x19038AEAU
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_SETTLE_FNV1A32 0xAF5725C0U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_PROJECTION_FNV1A32 0xCB8BD081U
#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_ACTOR_CLAMP_FNV1A32 0xCB1D4EAFU

#define TECMO_ASSET_PACK_GAMEPLAY_CAMERA_FNV1A32 0x53247856U

typedef struct TecmoGameplayCameraExpectedSource {
    TecmoGameplayCameraSourceKind kind;
    uint8_t bank;
    uint8_t fixed_bank;
    uint16_t cpu_start;
    uint32_t byte_count;
    uint32_t fingerprint;
    uint32_t payload_offset;
} TecmoGameplayCameraExpectedSource;

typedef struct TecmoGameplayCameraProvenance {
    uint64_t source_offsets[TECMO_GAMEPLAY_CAMERA_SOURCE_COUNT];
} TecmoGameplayCameraProvenance;

extern const TecmoGameplayCameraExpectedSource
    tecmo_gameplay_camera_expected_sources[
        TECMO_GAMEPLAY_CAMERA_SOURCE_COUNT];

int tecmo_asset_pack_build_gameplay_camera(
    const uint8_t *rom,
    uint64_t rom_size,
    uint64_t prg_offset,
    uint32_t prg_banks,
    int enforce_revision_fingerprints,
    uint8_t *payload,
    size_t payload_size,
    TecmoGameplayCameraProvenance *provenance,
    char *message,
    size_t message_size);

int tecmo_asset_pack_gameplay_camera_source_test(
    const char *rom_path,
    char *message,
    size_t message_size);

int tecmo_asset_pack_gameplay_camera_self_test(
    char *message,
    size_t message_size);

#endif
