#ifndef TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_H
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_H

#include "tecmo_gameplay_cpu_steering.h"

#include <stddef.h>
#include <stdint.h>

#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_ID \
    "gameplay/cpu-steering"
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_VERSION 2U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_HEADER_SIZE 336U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_SOURCE_STRIDE 32U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_SOURCES_OFFSET 336U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_DESCRIPTOR_OFFSET 96U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_DESCRIPTOR_STRIDE 12U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_HANDLER_OFFSET 216U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_DIRECTION_OFFSET 88U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_CONTRACT_DESCRIPTOR_OFFSET \
    272U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_CONTRACT_DESCRIPTOR_SIZE \
    16U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_CONTRACT_RAW_OFFSET \
    288U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_CONTRACT_RAW_SIZE \
    42U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_CONTRACT_BANK 6U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_CONTRACT_CPU_START \
    0x88B0U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_CONTRACT_FNV1A32 \
    0xAD834719U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_POSE_LOW_OFFSET 26U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_POSE_HIGH_OFFSET 34U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_RECORD_A_OFFSET \
    0x0037U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_RECORD_B_OFFSET \
    0x004BU
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_RECORD_FNV1A32 \
    0x735536DEU
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_HANDLER_CPU_START \
    0x9146U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_HANDLER_SIZE 209U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_HANDLER_FNV1A32 \
    0xFA3E6C5EU
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_FINAL_TAIL_CPU_START \
    0x9208U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_FINAL_TAIL_SIZE 15U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_OPCODE15_FINAL_TAIL_FNV1A32 \
    0x839F9D07U

#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_ACTOR_DISPATCH_OFFSET 656U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_ACTOR_DISPATCH_SIZE 221U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_REFERENCE_DIRECTION_OFFSET 880U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_REFERENCE_DIRECTION_SIZE 258U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_TARGET_DIRECTION_OFFSET 1152U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_TARGET_DIRECTION_SIZE 444U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_DISPATCH_OFFSET 1600U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_DISPATCH_SIZE 81U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_HANDLERS_OFFSET 1696U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_HANDLERS_SIZE 1623U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_TARGET_APPLY_OFFSET 3328U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_TARGET_APPLY_SIZE 170U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_FORMATION_STREAM_OFFSET 3504U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_FORMATION_STREAM_SIZE 662U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_TRAMPOLINE_OFFSET 4176U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_TRAMPOLINE_SIZE 3U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_READER_OFFSET 4192U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_READER_SIZE 23U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_PLAY_COMMANDS_OFFSET 4224U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_PLAY_COMMANDS_SIZE 3400U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_SIZE 7632U

#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_ACTOR_DISPATCH_FNV1A32 \
    0x23BB7271U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_REFERENCE_DIRECTION_FNV1A32 \
    0xF866B06CU
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_TARGET_DIRECTION_FNV1A32 \
    0x9616E586U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_DISPATCH_FNV1A32 \
    0x9AD2BA91U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_HANDLERS_FNV1A32 \
    0x344298FEU
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_TARGET_APPLY_FNV1A32 \
    0xC82E6853U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_FORMATION_STREAM_FNV1A32 \
    0x47818A62U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_TRAMPOLINE_FNV1A32 \
    0x14B2472EU
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_COMMAND_READER_FNV1A32 \
    0x41C5B5C8U
#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_PLAY_COMMANDS_FNV1A32 \
    0x71331A96U

#define TECMO_ASSET_PACK_GAMEPLAY_CPU_STEERING_FNV1A32 0xC8CFFDC0U

typedef struct TecmoGameplayCpuSteeringExpectedSource {
    TecmoGameplayCpuSteeringSourceKind kind;
    uint8_t bank;
    uint8_t fixed_bank;
    uint16_t cpu_start;
    uint32_t byte_count;
    uint32_t fingerprint;
    uint32_t payload_offset;
} TecmoGameplayCpuSteeringExpectedSource;

typedef struct TecmoGameplayCpuSteeringProvenance {
    uint64_t source_offsets[TECMO_GAMEPLAY_CPU_STEERING_SOURCE_COUNT];
} TecmoGameplayCpuSteeringProvenance;

extern const TecmoGameplayCpuSteeringExpectedSource
    tecmo_gameplay_cpu_steering_expected_sources[
        TECMO_GAMEPLAY_CPU_STEERING_SOURCE_COUNT];

int tecmo_asset_pack_build_gameplay_cpu_steering(
    const uint8_t *rom,
    uint64_t rom_size,
    uint64_t prg_offset,
    uint32_t prg_banks,
    int enforce_revision_fingerprints,
    uint8_t *payload,
    size_t payload_size,
    TecmoGameplayCpuSteeringProvenance *provenance,
    char *message,
    size_t message_size);
int tecmo_asset_pack_gameplay_cpu_steering_source_test(
    const char *rom_path,
    char *message,
    size_t message_size);
int tecmo_asset_pack_gameplay_cpu_steering_self_test(
    char *message,
    size_t message_size);

#endif
